spring:
  datasource:
    url: jdbc:mysql://192.168.67.133:3306/home_credit?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource

    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false


#  mybatis.mapper-locations=classpath*:mapper/*.xml
#  mybatis.type-aliases-package=com.raoqiang.redpacket.entity
#
#  mybatis.configuration.map-underscore-to-camel-case=true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.raoqiang.homecredit.entity
  configuration:
    map-underscore-to-camel-case: true