package com.raoqiang.homecredit.calculate;

public class StringUtils {

    public static final String standard = "AMT_ANNUITY\n" +
            "AMT_CREDIT\n" +
            "AMT_GOODS_PRICE\n" +
            "AMT_INCOME_TOTAL\n" +
            "AMT_REQ_CREDIT_BUREAU_HOUR\n" +
            "AMT_REQ_CREDIT_BUREAU_QRT\n" +
            "AMT_REQ_CREDIT_BUREAU_WEEK\n" +
            "APARTMENTS_AVG\n" +
            "APARTMENTS_MEDI\n" +
            "APARTMENTS_MODE\n" +
            "CODE_GENDER\n" +
            "DAYS_BIRTH\n" +
            "DAYS_EMPLOYED\n" +
            "DAYS_ID_PUBLISH\n" +
            "DAYS_LAST_PHONE_CHANGE\n" +
            "DAYS_REGISTRATION\n" +
            "DEF_30_CNT_SOCIAL_CIRCLE\n" +
            "DEF_60_CNT_SOCIAL_CIRCLE\n" +
            "ENTRANCES_AVG\n" +
            "ENTRANCES_MEDI\n" +
            "EXT_SOURCE_1\n" +
            "EXT_SOURCE_2\n" +
            "EXT_SOURCE_3\n" +
            "FLAG_DOCUMENT_18\n" +
            "FLAG_DOCUMENT_3\n" +
            "FLAG_DOCUMENT_8\n" +
            "FLAG_OWN_CAR\n" +
            "FLAG_WORK_PHONE\n" +
            "FLOORSMAX_AVG\n" +
            "FLOORSMAX_MEDI\n" +
            "FLOORSMAX_MODE\n" +
            "LIVE_CITY_NOT_WORK_CITY\n" +
            "LIVE_REGION_NOT_WORK_REGION\n" +
            "LIVINGAREA_AVG\n" +
            "NAME_CONTRACT_TYPE\n" +
            "NAME_EDUCATION_TYPE\n" +
            "NAME_FAMILY_STATUS\n" +
            "NAME_HOUSING_TYPE\n" +
            "NAME_INCOME_TYPE\n" +
            "NAME_TYPE_SUITE\n" +
            "OCCUPATION_TYPE\n" +
            "ORGANIZATION_TYPE\n" +
            "OWN_CAR_AGE\n" +
            "REGION_POPULATION_RELATIVE\n" +
            "REGION_RATING_CLIENT\n" +
            "REGION_RATING_CLIENT_W_CITY\n" +
            "REG_CITY_NOT_LIVE_CITY\n" +
            "TOTALAREA_MODE\n" +
            "WALLSMATERIAL_MODE\n" +
            "WEEKDAY_APPR_PROCESS_START\n" +
            "YEARS_BEGINEXPLUATATION_MEDI\n" +
            "DOCUMENT_COUNT\n" +
            "NEW_DOC_KURT\n" +
            "AGE_RANGE\n" +
            "EXT_SOURCES_PROD\n" +
            "EXT_SOURCES_WEIGHTED\n" +
            "EXT_SOURCES_MIN\n" +
            "EXT_SOURCES_MAX\n" +
            "EXT_SOURCES_MEAN\n" +
            "EXT_SOURCES_NANMEDIAN\n" +
            "EXT_SOURCES_VAR\n" +
            "CREDIT_TO_ANNUITY_RATIO\n" +
            "CREDIT_TO_GOODS_RATIO\n" +
            "ANNUITY_TO_INCOME_RATIO\n" +
            "CREDIT_TO_INCOME_RATIO\n" +
            "INCOME_TO_EMPLOYED_RATIO\n" +
            "INCOME_TO_BIRTH_RATIO\n" +
            "EMPLOYED_TO_BIRTH_RATIO\n" +
            "ID_TO_BIRTH_RATIO\n" +
            "CAR_TO_BIRTH_RATIO\n" +
            "CAR_TO_EMPLOYED_RATIO\n" +
            "PHONE_TO_BIRTH_RATIO\n" +
            "GROUP_EXT_SOURCES_MEDIAN\n" +
            "GROUP_EXT_SOURCES_STD\n" +
            "GROUP_INCOME_MEAN\n" +
            "GROUP_INCOME_STD\n" +
            "GROUP_CREDIT_TO_ANNUITY_MEAN\n" +
            "GROUP_CREDIT_TO_ANNUITY_STD\n" +
            "GROUP_CREDIT_MEAN\n" +
            "GROUP_ANNUITY_MEAN\n" +
            "GROUP_ANNUITY_STD\n" +
            "BUREAU_SK_ID_BUREAU_NUNIQUE\n" +
            "BUREAU_DAYS_CREDIT_MIN\n" +
            "BUREAU_DAYS_CREDIT_MAX\n" +
            "BUREAU_DAYS_CREDIT_MEAN\n" +
            "BUREAU_DAYS_CREDIT_ENDDATE_MIN\n" +
            "BUREAU_DAYS_CREDIT_ENDDATE_MAX\n" +
            "BUREAU_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_AMT_CREDIT_SUM_MEAN\n" +
            "BUREAU_AMT_CREDIT_SUM_SUM\n" +
            "BUREAU_AMT_CREDIT_SUM_DEBT_MAX\n" +
            "BUREAU_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_AMT_CREDIT_SUM_DEBT_SUM\n" +
            "BUREAU_AMT_CREDIT_SUM_OVERDUE_MAX\n" +
            "BUREAU_AMT_CREDIT_SUM_OVERDUE_MEAN\n" +
            "BUREAU_AMT_CREDIT_SUM_OVERDUE_SUM\n" +
            "BUREAU_AMT_ANNUITY_MEAN\n" +
            "BUREAU_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_DEBT_CREDIT_DIFF_SUM\n" +
            "BUREAU_MONTHS_BALANCE_MEAN_MEAN\n" +
            "BUREAU_MONTHS_BALANCE_MEAN_VAR\n" +
            "BUREAU_MONTHS_BALANCE_SIZE_MEAN\n" +
            "BUREAU_MONTHS_BALANCE_SIZE_SUM\n" +
            "BUREAU_STATUS_0_MEAN\n" +
            "BUREAU_STATUS_1_MEAN\n" +
            "BUREAU_STATUS_12345_MEAN\n" +
            "BUREAU_STATUS_C_MEAN\n" +
            "BUREAU_STATUS_X_MEAN\n" +
            "BUREAU_CREDIT_ACTIVE_Active_MEAN\n" +
            "BUREAU_CREDIT_ACTIVE_Closed_MEAN\n" +
            "BUREAU_CREDIT_ACTIVE_Sold_MEAN\n" +
            "BUREAU_CREDIT_TYPE_Consumer_credit_MEAN\n" +
            "BUREAU_CREDIT_TYPE_Credit_card_MEAN\n" +
            "BUREAU_CREDIT_TYPE_Car_loan_MEAN\n" +
            "BUREAU_CREDIT_TYPE_Mortgage_MEAN\n" +
            "BUREAU_CREDIT_TYPE_Microloan_MEAN\n" +
            "BUREAU_LL_AMT_CREDIT_SUM_OVERDUE_MEAN\n" +
            "BUREAU_LL_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_LL_STATUS_12345_MEAN\n" +
            "BUREAU_ACTIVE_DAYS_CREDIT_MAX\n" +
            "BUREAU_ACTIVE_DAYS_CREDIT_MEAN\n" +
            "BUREAU_ACTIVE_DAYS_CREDIT_ENDDATE_MIN\n" +
            "BUREAU_ACTIVE_DAYS_CREDIT_ENDDATE_MAX\n" +
            "BUREAU_ACTIVE_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_ACTIVE_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_ACTIVE_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_ACTIVE_AMT_CREDIT_SUM_SUM\n" +
            "BUREAU_ACTIVE_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_ACTIVE_AMT_CREDIT_SUM_DEBT_SUM\n" +
            "BUREAU_ACTIVE_AMT_CREDIT_SUM_OVERDUE_MAX\n" +
            "BUREAU_ACTIVE_AMT_CREDIT_SUM_OVERDUE_MEAN\n" +
            "BUREAU_ACTIVE_DAYS_CREDIT_UPDATE_MIN\n" +
            "BUREAU_ACTIVE_DAYS_CREDIT_UPDATE_MEAN\n" +
            "BUREAU_ACTIVE_DEBT_PERCENTAGE_MEAN\n" +
            "BUREAU_ACTIVE_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_ACTIVE_CREDIT_TO_ANNUITY_RATIO_MEAN\n" +
            "BUREAU_ACTIVE_MONTHS_BALANCE_MEAN_MEAN\n" +
            "BUREAU_ACTIVE_MONTHS_BALANCE_MEAN_VAR\n" +
            "BUREAU_ACTIVE_MONTHS_BALANCE_SIZE_MEAN\n" +
            "BUREAU_ACTIVE_MONTHS_BALANCE_SIZE_SUM\n" +
            "BUREAU_CLOSED_DAYS_CREDIT_MAX\n" +
            "BUREAU_CLOSED_DAYS_CREDIT_VAR\n" +
            "BUREAU_CLOSED_DAYS_CREDIT_ENDDATE_MAX\n" +
            "BUREAU_CLOSED_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_CLOSED_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_CLOSED_AMT_CREDIT_SUM_OVERDUE_MEAN\n" +
            "BUREAU_CLOSED_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_CLOSED_AMT_CREDIT_SUM_MEAN\n" +
            "BUREAU_CLOSED_AMT_CREDIT_SUM_SUM\n" +
            "BUREAU_CLOSED_AMT_CREDIT_SUM_DEBT_MAX\n" +
            "BUREAU_CLOSED_AMT_CREDIT_SUM_DEBT_SUM\n" +
            "BUREAU_CLOSED_DAYS_CREDIT_UPDATE_MAX\n" +
            "BUREAU_CLOSED_ENDDATE_DIF_MEAN\n" +
            "BUREAU_CLOSED_STATUS_12345_MEAN\n" +
            "BUREAU_CONSUMER_DAYS_CREDIT_MEAN\n" +
            "BUREAU_CONSUMER_DAYS_CREDIT_MAX\n" +
            "BUREAU_CONSUMER_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_CONSUMER_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_CONSUMER_AMT_CREDIT_SUM_MEAN\n" +
            "BUREAU_CONSUMER_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_CONSUMER_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_CONSUMER_AMT_CREDIT_SUM_DEBT_MAX\n" +
            "BUREAU_CONSUMER_DEBT_PERCENTAGE_MEAN\n" +
            "BUREAU_CONSUMER_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_CONSUMER_DAYS_CREDIT_ENDDATE_MAX\n" +
            "BUREAU_CREDIT_DAYS_CREDIT_MEAN\n" +
            "BUREAU_CREDIT_DAYS_CREDIT_MAX\n" +
            "BUREAU_CREDIT_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_CREDIT_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_CREDIT_AMT_CREDIT_SUM_MEAN\n" +
            "BUREAU_CREDIT_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_CREDIT_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_CREDIT_AMT_CREDIT_SUM_DEBT_MAX\n" +
            "BUREAU_CREDIT_DEBT_PERCENTAGE_MEAN\n" +
            "BUREAU_CREDIT_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_CREDIT_DAYS_CREDIT_ENDDATE_MAX\n" +
            "BUREAU_MORTGAGE_DAYS_CREDIT_MEAN\n" +
            "BUREAU_MORTGAGE_DAYS_CREDIT_MAX\n" +
            "BUREAU_MORTGAGE_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_MORTGAGE_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_MORTGAGE_AMT_CREDIT_SUM_MEAN\n" +
            "BUREAU_MORTGAGE_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_MORTGAGE_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_MORTGAGE_AMT_CREDIT_SUM_DEBT_MAX\n" +
            "BUREAU_MORTGAGE_DEBT_PERCENTAGE_MEAN\n" +
            "BUREAU_MORTGAGE_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_MORTGAGE_DAYS_CREDIT_ENDDATE_MAX\n" +
            "BUREAU_CAR_DAYS_CREDIT_MEAN\n" +
            "BUREAU_CAR_DAYS_CREDIT_MAX\n" +
            "BUREAU_CAR_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_CAR_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_CAR_AMT_CREDIT_SUM_MEAN\n" +
            "BUREAU_CAR_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_CAR_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_CAR_AMT_CREDIT_SUM_DEBT_MAX\n" +
            "BUREAU_CAR_DEBT_PERCENTAGE_MEAN\n" +
            "BUREAU_CAR_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_CAR_DAYS_CREDIT_ENDDATE_MAX\n" +
            "BUREAU_MICROLOAN_DAYS_CREDIT_MEAN\n" +
            "BUREAU_MICROLOAN_DAYS_CREDIT_MAX\n" +
            "BUREAU_MICROLOAN_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_MICROLOAN_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_MICROLOAN_AMT_CREDIT_SUM_MEAN\n" +
            "BUREAU_MICROLOAN_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_MICROLOAN_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_MICROLOAN_AMT_CREDIT_SUM_DEBT_MAX\n" +
            "BUREAU_MICROLOAN_DEBT_PERCENTAGE_MEAN\n" +
            "BUREAU_MICROLOAN_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_MICROLOAN_DAYS_CREDIT_ENDDATE_MAX\n" +
            "BUREAU_LAST6M_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_LAST6M_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_LAST6M_AMT_CREDIT_SUM_OVERDUE_MEAN\n" +
            "BUREAU_LAST6M_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_LAST6M_AMT_CREDIT_SUM_SUM\n" +
            "BUREAU_LAST6M_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_LAST6M_AMT_CREDIT_SUM_DEBT_SUM\n" +
            "BUREAU_LAST6M_DEBT_PERCENTAGE_MEAN\n" +
            "BUREAU_LAST6M_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_LAST6M_STATUS_0_MEAN\n" +
            "BUREAU_LAST6M_STATUS_12345_MEAN\n" +
            "BUREAU_LAST12M_AMT_CREDIT_MAX_OVERDUE_MAX\n" +
            "BUREAU_LAST12M_AMT_CREDIT_MAX_OVERDUE_MEAN\n" +
            "BUREAU_LAST12M_AMT_CREDIT_SUM_OVERDUE_MEAN\n" +
            "BUREAU_LAST12M_AMT_CREDIT_SUM_MAX\n" +
            "BUREAU_LAST12M_AMT_CREDIT_SUM_SUM\n" +
            "BUREAU_LAST12M_AMT_CREDIT_SUM_DEBT_MEAN\n" +
            "BUREAU_LAST12M_AMT_CREDIT_SUM_DEBT_SUM\n" +
            "BUREAU_LAST12M_DEBT_PERCENTAGE_MEAN\n" +
            "BUREAU_LAST12M_DEBT_CREDIT_DIFF_MEAN\n" +
            "BUREAU_LAST12M_STATUS_0_MEAN\n" +
            "BUREAU_LAST12M_STATUS_12345_MEAN\n" +
            "BUREAU_LAST_LOAN_MAX_OVERDUE\n" +
            "BUREAU_DEBT_OVER_CREDIT\n" +
            "BUREAU_ACTIVE_DEBT_OVER_CREDIT\n" +
            "PREV_SK_ID_PREV_NUNIQUE\n" +
            "PREV_AMT_ANNUITY_MIN\n" +
            "PREV_AMT_ANNUITY_MAX\n" +
            "PREV_AMT_ANNUITY_MEAN\n" +
            "PREV_AMT_DOWN_PAYMENT_MAX\n" +
            "PREV_AMT_DOWN_PAYMENT_MEAN\n" +
            "PREV_HOUR_APPR_PROCESS_START_MIN\n" +
            "PREV_HOUR_APPR_PROCESS_START_MAX\n" +
            "PREV_HOUR_APPR_PROCESS_START_MEAN\n" +
            "PREV_RATE_DOWN_PAYMENT_MAX\n" +
            "PREV_RATE_DOWN_PAYMENT_MEAN\n" +
            "PREV_DAYS_DECISION_MIN\n" +
            "PREV_DAYS_DECISION_MAX\n" +
            "PREV_DAYS_DECISION_MEAN\n" +
            "PREV_CNT_PAYMENT_MAX\n" +
            "PREV_CNT_PAYMENT_MEAN\n" +
            "PREV_DAYS_TERMINATION_MAX\n" +
            "PREV_CREDIT_TO_ANNUITY_RATIO_MEAN\n" +
            "PREV_CREDIT_TO_ANNUITY_RATIO_MAX\n" +
            "PREV_APPLICATION_CREDIT_DIFF_MIN\n" +
            "PREV_APPLICATION_CREDIT_DIFF_MAX\n" +
            "PREV_APPLICATION_CREDIT_DIFF_MEAN\n" +
            "PREV_APPLICATION_CREDIT_RATIO_MIN\n" +
            "PREV_APPLICATION_CREDIT_RATIO_MAX\n" +
            "PREV_APPLICATION_CREDIT_RATIO_MEAN\n" +
            "PREV_APPLICATION_CREDIT_RATIO_VAR\n" +
            "PREV_DOWN_PAYMENT_TO_CREDIT_MEAN\n" +
            "PREV_NAME_CONTRACT_STATUS_Approved_MEAN\n" +
            "PREV_NAME_CONTRACT_STATUS_Canceled_MEAN\n" +
            "PREV_NAME_CONTRACT_STATUS_Refused_MEAN\n" +
            "PREV_NAME_CONTRACT_STATUS_Unused_offer_MEAN\n" +
            "PREV_NAME_CONTRACT_TYPE_Cash_loans_MEAN\n" +
            "PREV_NAME_CONTRACT_TYPE_Consumer_loans_MEAN\n" +
            "PREV_NAME_CONTRACT_TYPE_Revolving_loans_MEAN\n" +
            "PREV_NAME_CONTRACT_TYPE_XNA_MEAN\n" +
            "PREV_CHANNEL_TYPE_AP+_(Cash_loan)_MEAN\n" +
            "PREV_CHANNEL_TYPE_Car_dealer_MEAN\n" +
            "PREV_CHANNEL_TYPE_Channel_of_corporate_sales_MEAN\n" +
            "PREV_CHANNEL_TYPE_Contact_center_MEAN\n" +
            "PREV_CHANNEL_TYPE_Country-wide_MEAN\n" +
            "PREV_CHANNEL_TYPE_Credit_and_cash_offices_MEAN\n" +
            "PREV_CHANNEL_TYPE_Regional_/_Local_MEAN\n" +
            "PREV_CHANNEL_TYPE_Stone_MEAN\n" +
            "PREV_NAME_TYPE_SUITE_Children_MEAN\n" +
            "PREV_NAME_TYPE_SUITE_Family_MEAN\n" +
            "PREV_NAME_TYPE_SUITE_Group_of_people_MEAN\n" +
            "PREV_NAME_TYPE_SUITE_Other_A_MEAN\n" +
            "PREV_NAME_TYPE_SUITE_Other_B_MEAN\n" +
            "PREV_NAME_TYPE_SUITE_Spouse,_partner_MEAN\n" +
            "PREV_NAME_TYPE_SUITE_Unaccompanied_MEAN\n" +
            "PREV_NAME_YIELD_GROUP_XNA_MEAN\n" +
            "PREV_NAME_YIELD_GROUP_high_MEAN\n" +
            "PREV_NAME_YIELD_GROUP_low_action_MEAN\n" +
            "PREV_NAME_YIELD_GROUP_low_normal_MEAN\n" +
            "PREV_NAME_YIELD_GROUP_middle_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Card_Street_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Card_X-Sell_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Cash_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Cash_Street:_high_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Cash_Street:_low_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Cash_Street:_middle_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Cash_X-Sell:_high_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Cash_X-Sell:_low_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_Cash_X-Sell:_middle_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_POS_household_with_interest_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_POS_household_without_interest_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_POS_industry_with_interest_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_POS_industry_without_interest_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_POS_mobile_with_interest_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_POS_mobile_without_interest_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_POS_other_with_interest_MEAN\n" +
            "PREV_PRODUCT_COMBINATION_POS_others_without_interest_MEAN\n" +
            "PREV_NAME_PRODUCT_TYPE_XNA_MEAN\n" +
            "PREV_NAME_PRODUCT_TYPE_walk-in_MEAN\n" +
            "PREV_NAME_PRODUCT_TYPE_x-sell_MEAN\n" +
            "PREV_NAME_CLIENT_TYPE_New_MEAN\n" +
            "PREV_NAME_CLIENT_TYPE_Refreshed_MEAN\n" +
            "PREV_NAME_CLIENT_TYPE_Repeater_MEAN\n" +
            "PREV_NAME_CLIENT_TYPE_XNA_MEAN\n" +
            "PREV_ACTIVE_SK_ID_PREV_NUNIQUE\n" +
            "PREV_ACTIVE_SIMPLE_INTERESTS_MEAN\n" +
            "PREV_ACTIVE_AMT_ANNUITY_MAX\n" +
            "PREV_ACTIVE_AMT_ANNUITY_SUM\n" +
            "PREV_ACTIVE_AMT_APPLICATION_MAX\n" +
            "PREV_ACTIVE_AMT_APPLICATION_MEAN\n" +
            "PREV_ACTIVE_AMT_CREDIT_SUM\n" +
            "PREV_ACTIVE_AMT_DOWN_PAYMENT_MAX\n" +
            "PREV_ACTIVE_AMT_DOWN_PAYMENT_MEAN\n" +
            "PREV_ACTIVE_DAYS_DECISION_MIN\n" +
            "PREV_ACTIVE_DAYS_DECISION_MEAN\n" +
            "PREV_ACTIVE_CNT_PAYMENT_MEAN\n" +
            "PREV_ACTIVE_CNT_PAYMENT_SUM\n" +
            "PREV_ACTIVE_DAYS_LAST_DUE_1ST_VERSION_MIN\n" +
            "PREV_ACTIVE_DAYS_LAST_DUE_1ST_VERSION_MAX\n" +
            "PREV_ACTIVE_DAYS_LAST_DUE_1ST_VERSION_MEAN\n" +
            "PREV_ACTIVE_AMT_PAYMENT_SUM\n" +
            "PREV_ACTIVE_INSTALMENT_PAYMENT_DIFF_MEAN\n" +
            "PREV_ACTIVE_INSTALMENT_PAYMENT_DIFF_MAX\n" +
            "PREV_ACTIVE_REMAINING_DEBT_MAX\n" +
            "PREV_ACTIVE_REMAINING_DEBT_MEAN\n" +
            "PREV_ACTIVE_REMAINING_DEBT_SUM\n" +
            "PREV_ACTIVE_REPAYMENT_RATIO_MEAN\n" +
            "TOTAL_REPAYMENT_RATIO\n" +
            "APPROVED_SK_ID_PREV_NUNIQUE\n" +
            "APPROVED_AMT_ANNUITY_MIN\n" +
            "APPROVED_AMT_ANNUITY_MAX\n" +
            "APPROVED_AMT_ANNUITY_MEAN\n" +
            "APPROVED_AMT_CREDIT_MIN\n" +
            "APPROVED_AMT_CREDIT_MAX\n" +
            "APPROVED_AMT_CREDIT_MEAN\n" +
            "APPROVED_AMT_DOWN_PAYMENT_MAX\n" +
            "APPROVED_AMT_GOODS_PRICE_MAX\n" +
            "APPROVED_HOUR_APPR_PROCESS_START_MIN\n" +
            "APPROVED_HOUR_APPR_PROCESS_START_MAX\n" +
            "APPROVED_DAYS_DECISION_MIN\n" +
            "APPROVED_DAYS_DECISION_MEAN\n" +
            "APPROVED_CNT_PAYMENT_MAX\n" +
            "APPROVED_CNT_PAYMENT_MEAN\n" +
            "APPROVED_DAYS_TERMINATION_MEAN\n" +
            "APPROVED_CREDIT_TO_ANNUITY_RATIO_MEAN\n" +
            "APPROVED_CREDIT_TO_ANNUITY_RATIO_MAX\n" +
            "APPROVED_APPLICATION_CREDIT_DIFF_MAX\n" +
            "APPROVED_APPLICATION_CREDIT_RATIO_MIN\n" +
            "APPROVED_APPLICATION_CREDIT_RATIO_MAX\n" +
            "APPROVED_APPLICATION_CREDIT_RATIO_MEAN\n" +
            "APPROVED_DAYS_FIRST_DRAWING_MAX\n" +
            "APPROVED_DAYS_FIRST_DRAWING_MEAN\n" +
            "APPROVED_DAYS_FIRST_DUE_MIN\n" +
            "APPROVED_DAYS_FIRST_DUE_MEAN\n" +
            "APPROVED_DAYS_LAST_DUE_1ST_VERSION_MIN\n" +
            "APPROVED_DAYS_LAST_DUE_1ST_VERSION_MAX\n" +
            "APPROVED_DAYS_LAST_DUE_1ST_VERSION_MEAN\n" +
            "APPROVED_DAYS_LAST_DUE_MAX\n" +
            "APPROVED_DAYS_LAST_DUE_MEAN\n" +
            "APPROVED_DAYS_LAST_DUE_DIFF_MIN\n" +
            "APPROVED_DAYS_LAST_DUE_DIFF_MAX\n" +
            "APPROVED_DAYS_LAST_DUE_DIFF_MEAN\n" +
            "APPROVED_SIMPLE_INTERESTS_MIN\n" +
            "APPROVED_SIMPLE_INTERESTS_MAX\n" +
            "APPROVED_SIMPLE_INTERESTS_MEAN\n" +
            "REFUSED_AMT_APPLICATION_MAX\n" +
            "REFUSED_AMT_APPLICATION_MEAN\n" +
            "REFUSED_AMT_CREDIT_MIN\n" +
            "REFUSED_AMT_CREDIT_MAX\n" +
            "REFUSED_DAYS_DECISION_MIN\n" +
            "REFUSED_DAYS_DECISION_MAX\n" +
            "REFUSED_DAYS_DECISION_MEAN\n" +
            "REFUSED_CNT_PAYMENT_MAX\n" +
            "REFUSED_CNT_PAYMENT_MEAN\n" +
            "REFUSED_APPLICATION_CREDIT_DIFF_MIN\n" +
            "REFUSED_APPLICATION_CREDIT_DIFF_MAX\n" +
            "REFUSED_APPLICATION_CREDIT_DIFF_MEAN\n" +
            "REFUSED_APPLICATION_CREDIT_DIFF_VAR\n" +
            "REFUSED_APPLICATION_CREDIT_RATIO_MIN\n" +
            "REFUSED_APPLICATION_CREDIT_RATIO_MEAN\n" +
            "REFUSED_NAME_CONTRACT_TYPE_Consumer_loans_MEAN\n" +
            "REFUSED_NAME_CONTRACT_TYPE_Cash_loans_MEAN\n" +
            "REFUSED_NAME_CONTRACT_TYPE_Revolving_loans_MEAN\n" +
            "PREV_Consumer_AMT_CREDIT_SUM\n" +
            "PREV_Consumer_AMT_ANNUITY_MEAN\n" +
            "PREV_Consumer_AMT_ANNUITY_MAX\n" +
            "PREV_Consumer_SIMPLE_INTERESTS_MIN\n" +
            "PREV_Consumer_SIMPLE_INTERESTS_MEAN\n" +
            "PREV_Consumer_SIMPLE_INTERESTS_MAX\n" +
            "PREV_Consumer_SIMPLE_INTERESTS_VAR\n" +
            "PREV_Consumer_APPLICATION_CREDIT_DIFF_MIN\n" +
            "PREV_Consumer_APPLICATION_CREDIT_DIFF_VAR\n" +
            "PREV_Consumer_APPLICATION_CREDIT_RATIO_MIN\n" +
            "PREV_Consumer_APPLICATION_CREDIT_RATIO_MAX\n" +
            "PREV_Consumer_APPLICATION_CREDIT_RATIO_MEAN\n" +
            "PREV_Consumer_DAYS_DECISION_MAX\n" +
            "PREV_Consumer_DAYS_LAST_DUE_1ST_VERSION_MAX\n" +
            "PREV_Consumer_DAYS_LAST_DUE_1ST_VERSION_MEAN\n" +
            "PREV_Consumer_CNT_PAYMENT_MEAN\n" +
            "PREV_Cash_AMT_CREDIT_SUM\n" +
            "PREV_Cash_AMT_ANNUITY_MEAN\n" +
            "PREV_Cash_AMT_ANNUITY_MAX\n" +
            "PREV_Cash_SIMPLE_INTERESTS_MIN\n" +
            "PREV_Cash_SIMPLE_INTERESTS_MEAN\n" +
            "PREV_Cash_SIMPLE_INTERESTS_MAX\n" +
            "PREV_Cash_SIMPLE_INTERESTS_VAR\n" +
            "PREV_Cash_APPLICATION_CREDIT_DIFF_MIN\n" +
            "PREV_Cash_APPLICATION_CREDIT_DIFF_VAR\n" +
            "PREV_Cash_APPLICATION_CREDIT_RATIO_MIN\n" +
            "PREV_Cash_APPLICATION_CREDIT_RATIO_MAX\n" +
            "PREV_Cash_APPLICATION_CREDIT_RATIO_MEAN\n" +
            "PREV_Cash_DAYS_DECISION_MAX\n" +
            "PREV_Cash_DAYS_LAST_DUE_1ST_VERSION_MAX\n" +
            "PREV_Cash_DAYS_LAST_DUE_1ST_VERSION_MEAN\n" +
            "PREV_Cash_CNT_PAYMENT_MEAN\n" +
            "PREV_LATE_DAYS_DECISION_MIN\n" +
            "PREV_LATE_DAYS_DECISION_MAX\n" +
            "PREV_LATE_DAYS_DECISION_MEAN\n" +
            "PREV_LATE_DAYS_LAST_DUE_1ST_VERSION_MIN\n" +
            "PREV_LATE_DAYS_LAST_DUE_1ST_VERSION_MAX\n" +
            "PREV_LATE_DAYS_LAST_DUE_1ST_VERSION_MEAN\n" +
            "PREV_LATE_APPLICATION_CREDIT_DIFF_MIN\n" +
            "PREV_LATE_NAME_CONTRACT_TYPE_Consumer_loans_MEAN\n" +
            "PREV_LATE_NAME_CONTRACT_TYPE_Cash_loans_MEAN\n" +
            "PREV_LATE_NAME_CONTRACT_TYPE_Revolving_loans_MEAN\n" +
            "PREV_LAST12M_AMT_CREDIT_SUM\n" +
            "PREV_LAST12M_AMT_ANNUITY_MEAN\n" +
            "PREV_LAST12M_AMT_ANNUITY_MAX\n" +
            "PREV_LAST12M_SIMPLE_INTERESTS_MEAN\n" +
            "PREV_LAST12M_SIMPLE_INTERESTS_MAX\n" +
            "PREV_LAST12M_DAYS_DECISION_MIN\n" +
            "PREV_LAST12M_DAYS_DECISION_MEAN\n" +
            "PREV_LAST12M_DAYS_LAST_DUE_1ST_VERSION_MIN\n" +
            "PREV_LAST12M_DAYS_LAST_DUE_1ST_VERSION_MAX\n" +
            "PREV_LAST12M_DAYS_LAST_DUE_1ST_VERSION_MEAN\n" +
            "PREV_LAST12M_APPLICATION_CREDIT_DIFF_MIN\n" +
            "PREV_LAST12M_APPLICATION_CREDIT_RATIO_MIN\n" +
            "PREV_LAST12M_APPLICATION_CREDIT_RATIO_MAX\n" +
            "PREV_LAST12M_APPLICATION_CREDIT_RATIO_MEAN\n" +
            "PREV_LAST12M_NAME_CONTRACT_TYPE_Consumer_loans_MEAN\n" +
            "PREV_LAST12M_NAME_CONTRACT_TYPE_Cash_loans_MEAN\n" +
            "PREV_LAST12M_NAME_CONTRACT_TYPE_Revolving_loans_MEAN\n" +
            "PREV_LAST24M_AMT_CREDIT_SUM\n" +
            "PREV_LAST24M_AMT_ANNUITY_MEAN\n" +
            "PREV_LAST24M_AMT_ANNUITY_MAX\n" +
            "PREV_LAST24M_SIMPLE_INTERESTS_MEAN\n" +
            "PREV_LAST24M_SIMPLE_INTERESTS_MAX\n" +
            "PREV_LAST24M_DAYS_DECISION_MIN\n" +
            "PREV_LAST24M_DAYS_DECISION_MEAN\n" +
            "PREV_LAST24M_DAYS_LAST_DUE_1ST_VERSION_MIN\n" +
            "PREV_LAST24M_DAYS_LAST_DUE_1ST_VERSION_MAX\n" +
            "PREV_LAST24M_DAYS_LAST_DUE_1ST_VERSION_MEAN\n" +
            "PREV_LAST24M_APPLICATION_CREDIT_DIFF_MIN\n" +
            "PREV_LAST24M_APPLICATION_CREDIT_RATIO_MIN\n" +
            "PREV_LAST24M_APPLICATION_CREDIT_RATIO_MAX\n" +
            "PREV_LAST24M_APPLICATION_CREDIT_RATIO_MEAN\n" +
            "PREV_LAST24M_NAME_CONTRACT_TYPE_Consumer_loans_MEAN\n" +
            "PREV_LAST24M_NAME_CONTRACT_TYPE_Cash_loans_MEAN\n" +
            "PREV_LAST24M_NAME_CONTRACT_TYPE_Revolving_loans_MEAN\n" +
            "POS_SK_ID_PREV_NUNIQUE\n" +
            "POS_MONTHS_BALANCE_MIN\n" +
            "POS_MONTHS_BALANCE_MAX\n" +
            "POS_MONTHS_BALANCE_SIZE\n" +
            "POS_SK_DPD_MAX\n" +
            "POS_SK_DPD_MEAN\n" +
            "POS_SK_DPD_SUM\n" +
            "POS_SK_DPD_VAR\n" +
            "POS_SK_DPD_DEF_MAX\n" +
            "POS_SK_DPD_DEF_MEAN\n" +
            "POS_SK_DPD_DEF_SUM\n" +
            "POS_LATE_PAYMENT_MEAN\n" +
            "POS_NAME_CONTRACT_STATUS_Active_MEAN\n" +
            "POS_NAME_CONTRACT_STATUS_Approved_MEAN\n" +
            "POS_NAME_CONTRACT_STATUS_Completed_MEAN\n" +
            "POS_NAME_CONTRACT_STATUS_Demand_MEAN\n" +
            "POS_NAME_CONTRACT_STATUS_Returned_to_the_store_MEAN\n" +
            "POS_NAME_CONTRACT_STATUS_Signed_MEAN\n" +
            "POS_LOAN_COMPLETED_MEAN\n" +
            "POS_COMPLETED_BEFORE_MEAN\n" +
            "POS_REMAINING_INSTALMENTS\n" +
            "POS_REMAINING_INSTALMENTS_RATIO\n" +
            "LATE_PAYMENT_SUM\n" +
            "INS_SK_ID_PREV_SIZE\n" +
            "INS_SK_ID_PREV_NUNIQUE\n" +
            "INS_DAYS_ENTRY_PAYMENT_MIN\n" +
            "INS_DAYS_ENTRY_PAYMENT_MAX\n" +
            "INS_DAYS_ENTRY_PAYMENT_MEAN\n" +
            "INS_AMT_INSTALMENT_MIN\n" +
            "INS_AMT_INSTALMENT_MAX\n" +
            "INS_AMT_INSTALMENT_MEAN\n" +
            "INS_AMT_INSTALMENT_SUM\n" +
            "INS_AMT_PAYMENT_MIN\n" +
            "INS_AMT_PAYMENT_MAX\n" +
            "INS_AMT_PAYMENT_MEAN\n" +
            "INS_AMT_PAYMENT_SUM\n" +
            "INS_DPD_MAX\n" +
            "INS_DPD_MEAN\n" +
            "INS_DPD_VAR\n" +
            "INS_DBD_MAX\n" +
            "INS_DBD_MEAN\n" +
            "INS_DBD_VAR\n" +
            "INS_PAYMENT_DIFFERENCE_MEAN\n" +
            "INS_PAYMENT_RATIO_MEAN\n" +
            "INS_LATE_PAYMENT_MEAN\n" +
            "INS_LATE_PAYMENT_SUM\n" +
            "INS_SIGNIFICANT_LATE_PAYMENT_MEAN\n" +
            "INS_SIGNIFICANT_LATE_PAYMENT_SUM\n" +
            "INS_LATE_PAYMENT_RATIO_MEAN\n" +
            "INS_DPD_7_MEAN\n" +
            "INS_DPD_15_MEAN\n" +
            "INS_PAID_OVER_MEAN\n" +
            "INS_36M_SK_ID_PREV_SIZE\n" +
            "INS_36M_DAYS_ENTRY_PAYMENT_MIN\n" +
            "INS_36M_DAYS_ENTRY_PAYMENT_MAX\n" +
            "INS_36M_DAYS_ENTRY_PAYMENT_MEAN\n" +
            "INS_36M_AMT_INSTALMENT_MIN\n" +
            "INS_36M_AMT_INSTALMENT_MAX\n" +
            "INS_36M_AMT_INSTALMENT_MEAN\n" +
            "INS_36M_AMT_INSTALMENT_SUM\n" +
            "INS_36M_AMT_PAYMENT_MIN\n" +
            "INS_36M_AMT_PAYMENT_MAX\n" +
            "INS_36M_AMT_PAYMENT_MEAN\n" +
            "INS_36M_AMT_PAYMENT_SUM\n" +
            "INS_36M_DPD_MAX\n" +
            "INS_36M_DPD_MEAN\n" +
            "INS_36M_DPD_VAR\n" +
            "INS_36M_DBD_MAX\n" +
            "INS_36M_DBD_MEAN\n" +
            "INS_36M_DBD_VAR\n" +
            "INS_36M_PAYMENT_DIFFERENCE_MEAN\n" +
            "INS_36M_PAYMENT_RATIO_MEAN\n" +
            "INS_36M_LATE_PAYMENT_MEAN\n" +
            "INS_36M_SIGNIFICANT_LATE_PAYMENT_MEAN\n" +
            "INS_36M_LATE_PAYMENT_RATIO_MEAN\n" +
            "INS_36M_DPD_7_MEAN\n" +
            "INS_36M_DPD_15_MEAN\n" +
            "INS_60M_SK_ID_PREV_SIZE\n" +
            "INS_60M_DAYS_ENTRY_PAYMENT_MIN\n" +
            "INS_60M_DAYS_ENTRY_PAYMENT_MAX\n" +
            "INS_60M_DAYS_ENTRY_PAYMENT_MEAN\n" +
            "INS_60M_AMT_INSTALMENT_MIN\n" +
            "INS_60M_AMT_INSTALMENT_MAX\n" +
            "INS_60M_AMT_INSTALMENT_MEAN\n" +
            "INS_60M_AMT_INSTALMENT_SUM\n" +
            "INS_60M_AMT_PAYMENT_MIN\n" +
            "INS_60M_AMT_PAYMENT_MAX\n" +
            "INS_60M_AMT_PAYMENT_MEAN\n" +
            "INS_60M_AMT_PAYMENT_SUM\n" +
            "INS_60M_DPD_MAX\n" +
            "INS_60M_DPD_MEAN\n" +
            "INS_60M_DPD_VAR\n" +
            "INS_60M_DBD_MAX\n" +
            "INS_60M_DBD_MEAN\n" +
            "INS_60M_DBD_VAR\n" +
            "INS_60M_PAYMENT_DIFFERENCE_MEAN\n" +
            "INS_60M_PAYMENT_RATIO_MEAN\n" +
            "INS_60M_LATE_PAYMENT_MEAN\n" +
            "INS_60M_SIGNIFICANT_LATE_PAYMENT_MEAN\n" +
            "INS_60M_LATE_PAYMENT_RATIO_MEAN\n" +
            "INS_60M_DPD_7_MEAN\n" +
            "INS_60M_DPD_15_MEAN\n" +
            "CC_MONTHS_BALANCE_MIN\n" +
            "CC_AMT_BALANCE_MAX\n" +
            "CC_AMT_CREDIT_LIMIT_ACTUAL_MAX\n" +
            "CC_AMT_DRAWINGS_ATM_CURRENT_MAX\n" +
            "CC_AMT_DRAWINGS_ATM_CURRENT_SUM\n" +
            "CC_AMT_DRAWINGS_CURRENT_MAX\n" +
            "CC_AMT_DRAWINGS_CURRENT_SUM\n" +
            "CC_AMT_DRAWINGS_POS_CURRENT_MAX\n" +
            "CC_AMT_DRAWINGS_POS_CURRENT_SUM\n" +
            "CC_AMT_INST_MIN_REGULARITY_MAX\n" +
            "CC_AMT_INST_MIN_REGULARITY_MEAN\n" +
            "CC_AMT_PAYMENT_TOTAL_CURRENT_MAX\n" +
            "CC_AMT_PAYMENT_TOTAL_CURRENT_MEAN\n" +
            "CC_AMT_PAYMENT_TOTAL_CURRENT_SUM\n" +
            "CC_AMT_PAYMENT_TOTAL_CURRENT_VAR\n" +
            "CC_AMT_TOTAL_RECEIVABLE_MAX\n" +
            "CC_AMT_TOTAL_RECEIVABLE_MEAN\n" +
            "CC_CNT_DRAWINGS_ATM_CURRENT_MAX\n" +
            "CC_CNT_DRAWINGS_ATM_CURRENT_MEAN\n" +
            "CC_CNT_DRAWINGS_ATM_CURRENT_SUM\n" +
            "CC_CNT_DRAWINGS_CURRENT_MAX\n" +
            "CC_CNT_DRAWINGS_CURRENT_MEAN\n" +
            "CC_CNT_DRAWINGS_CURRENT_SUM\n" +
            "CC_CNT_DRAWINGS_POS_CURRENT_MEAN\n" +
            "CC_SK_DPD_MEAN\n" +
            "CC_SK_DPD_MAX\n" +
            "CC_SK_DPD_SUM\n" +
            "CC_SK_DPD_DEF_MAX\n" +
            "CC_SK_DPD_DEF_SUM\n" +
            "CC_LIMIT_USE_MAX\n" +
            "CC_LIMIT_USE_MEAN\n" +
            "CC_PAYMENT_DIV_MIN_MIN\n" +
            "CC_PAYMENT_DIV_MIN_MEAN\n" +
            "CC_LATE_PAYMENT_MAX\n" +
            "CC_LATE_PAYMENT_SUM\n" +
            "CC_LAST_AMT_BALANCE_MEAN\n" +
            "CC_LAST_AMT_BALANCE_MAX\n" +
            "INS_12M_CNT_DRAWINGS_ATM_CURRENT_MEAN\n" +
            "INS_12M_SK_DPD_MAX\n" +
            "INS_12M_SK_DPD_SUM\n" +
            "INS_12M_AMT_BALANCE_MEAN\n" +
            "INS_12M_AMT_BALANCE_MAX\n" +
            "INS_12M_LIMIT_USE_MAX\n" +
            "INS_12M_LIMIT_USE_MEAN\n" +
            "INS_24M_CNT_DRAWINGS_ATM_CURRENT_MEAN\n" +
            "INS_24M_SK_DPD_MAX\n" +
            "INS_24M_SK_DPD_SUM\n" +
            "INS_24M_AMT_BALANCE_MEAN\n" +
            "INS_24M_AMT_BALANCE_MAX\n" +
            "INS_24M_LIMIT_USE_MAX\n" +
            "INS_24M_LIMIT_USE_MEAN\n" +
            "INS_48M_CNT_DRAWINGS_ATM_CURRENT_MEAN\n" +
            "INS_48M_SK_DPD_MAX\n" +
            "INS_48M_SK_DPD_SUM\n" +
            "INS_48M_AMT_BALANCE_MEAN\n" +
            "INS_48M_AMT_BALANCE_MAX\n" +
            "INS_48M_LIMIT_USE_MAX\n" +
            "INS_48M_LIMIT_USE_MEAN\n" +
            "BUREAU_INCOME_CREDIT_RATIO\n" +
            "BUREAU_ACTIVE_CREDIT_TO_INCOME_RATIO\n" +
            "CURRENT_TO_APPROVED_CREDIT_MIN_RATIO\n" +
            "CURRENT_TO_APPROVED_CREDIT_MAX_RATIO\n" +
            "CURRENT_TO_APPROVED_CREDIT_MEAN_RATIO\n" +
            "CURRENT_TO_APPROVED_ANNUITY_MAX_RATIO\n" +
            "CURRENT_TO_APPROVED_ANNUITY_MEAN_RATIO\n" +
            "PAYMENT_MIN_TO_ANNUITY_RATIO\n" +
            "PAYMENT_MAX_TO_ANNUITY_RATIO\n" +
            "PAYMENT_MEAN_TO_ANNUITY_RATIO\n" +
            "CTA_CREDIT_TO_ANNUITY_MAX_RATIO\n" +
            "CTA_CREDIT_TO_ANNUITY_MEAN_RATIO\n" +
            "DAYS_DECISION_MEAN_TO_BIRTH\n" +
            "DAYS_CREDIT_MEAN_TO_BIRTH\n" +
            "DAYS_DECISION_MEAN_TO_EMPLOYED\n" +
            "DAYS_CREDIT_MEAN_TO_EMPLOYED";


}
